### ISSUE TITLE
AttributeError: 'module' object has no attribute 'test_jieba_tokenizer'

### ISSUE THREAD

**Issue by liuxiaoan8008** [ybbaigo/sklearn-plus#2]
### Description

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    setup_requires=setup_requirements,
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py27/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/opt/python/2.7.14/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/python/2.7.14/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/opt/python/2.7.14/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_jieba_tokenizer'

### What I Did

```
I did nothing with test_jieba_tokenizer.py except added some docstring.
```

**Comment by liuxiaoan8008** [comment]
something wrong in test_jieba_tokenizer.py
