### ISSUE TITLE
python3.6 normalize.py tmp = re.sub(ur'^http.*$', u' ', tmp) SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by liuxiaoan8008** [ybbaigo/sklearn-plus#3]
### Description

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    setup_requires=setup_requirements,
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py36/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py36/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/opt/python/3.6.3/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/python/3.6.3/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/opt/python/3.6.3/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/build/ybbaigo/sklearn-plus/.tox/py36/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/travis/build/ybbaigo/sklearn-plus/tests/test_normalize.py", line 9, in <module>
    from sklearn_plus.preprocessing.text.zh.normalize import Normalizer
  File "/home/travis/build/ybbaigo/sklearn-plus/sklearn_plus/preprocessing/text/zh/normalize.py", line 24
    tmp = re.sub(ur'^http.*$', u' ', tmp)
                            ^
SyntaxError: invalid syntax

---
The normalize test passed in my machine(mac pro with python 2.7) , but can't pass the CI with python 3.6

**Comment by liuxiaoan8008** [comment]
python3 not support  'u' in regex
